version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - npm install eslint --save-dev
  build:
    commands:
      - npx eslint .
      - serverless deploy
